# Generated by Django 2.2.1 on 2019-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20190507_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='slug',
            field=models.SlugField(default='Matematica I', max_length=120),
            preserve_default=False,
        ),
    ]
