# Generated by Django 2.2.1 on 2019-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_aula_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
