# Generated by Django 2.2.1 on 2019-05-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20190507_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='num_sesion',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
