# Generated by Django 2.2.1 on 2019-05-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_aula_num_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='num_sesion',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
