# Generated by Django 2.2.1 on 2019-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
