# Generated by Django 2.2.1 on 2019-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_curso_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo_academico',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='curso',
            name='num_credito',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='curso',
            name='pre_requisito',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
