# Generated by Django 2.2.1 on 2019-05-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20190509_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='slug',
        ),
    ]
